---
# playbooks/cancel_subscription.yml
# CANCEL Subscription
# Segue la logica: RETRIEVE_SUBSCRIPTION -> ASSIGN_CANCELLED_ROLE

- name: Cancel Subscription
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Validate required variables
      assert:
        that:
          - provider_client_tag is defined and provider_client_tag != ""
          - external_id is defined and external_id != ""
        fail_msg: "Missing required variables: external_id, request_id or quota parameters (at least one quota must be defined)"

    - name: Debug all vars
      debug:
        msg: "{{ vars | dict2items | selectattr('key', 'search', 'credential|secret|yaml') | list }}"

    - name: Parse providers config map
      include_role:
        name: providers_secret_parse
      vars:
        provider_client_tag: "{{ provider_client_tag }}"
    - name: Save provider secret
      set_fact:
        provider_secret: "{{ provider_secret}}"

    # ========================================================================
    # EXECUTE CANCEL
    # ========================================================================
    - name: Execute Openstack Cancel Subscription Role
      include_role:
        name: openstack_subscription_cancel
      when: provider_secret.type == "openstack"
      vars:
        provider_client_tag: "{{ provider_client_tag }}"
        external_id: "{{ external_id }}"
        user_email: "{{ user_email }}"
        cloudblue_template_id: "{{ cloudblue_template_id }}"

    - name: Set workflow artifacts
      set_stats:
        data:
          provider_client_tag: "{{ provider_client_tag }}"
          request_id: "{{ request_id }}"
          external_id: "{{ external_id }}"
          user_email: "{{ user_email }}"
          cloudblue_template_id: "{{ cloudblue_template_id }}"
          provider_id: "{{ provider_secret.providerId }}"