---
# playbooks/change_subscription.yml
# CHANGE Subscription
# Segue la logica: RETRIEVE_SUBSCRIPTION_PROJECT -> SETUP_QUOTA

- name: Change Subscription Quotas
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Validate required variables
      assert:
        that:
          - provider_client_tag is defined and provider_client_tag != ""
          - external_id is defined and external_id != ""
        fail_msg: "Missing required variables: external_id, request_id or quota parameters (at least one quota must be defined)"
 
    - name: Debug all vars
      debug:
        msg: "{{ vars | dict2items | selectattr('key', 'search', 'credential|secret|yaml') | list }}"

    - name: Parse providers config map
      include_role:
        name: providers_secret_parse
      vars:
        provider_client_tag: "{{ provider_client_tag }}"
    - name: Save provider secret
      set_fact:
        provider_secret: "{{ provider_secret}}"


# Stessa cosa per tutte le autenticazioni 
    # ========================================================================
    # EXECUTE CHANGE
    # ========================================================================
    - name: Execute Openstack Change Subscription Role
      include_role:
        name: openstack_subscription_change
      when: provider_secret.type == "openstack"
      vars:
        provider_client_tag: "{{ provider_client_tag }}"
        external_id: "{{ external_id }}"
        quota_vcpu: "{{ quota_vcpu }}"
        quota_ram: "{{ quota_ram }}"
        quota_storage: "{{ quota_storage }}"
        quota_pub_ip: "{{ quota_pub_ip }}"
        quota_backup: "{{ quota_backup }}"
        user_email: "{{ user_email }}"
        cloudblue_template_id: "{{ cloudblue_template_id }}"

    - name: Set workflow artifacts
      set_stats:
        data:
          provider_client_tag: "{{ provider_client_tag }}"
          provider_id: "{{ provider_secret.providerId }}"
          provider_name: "{{ provider_secret.providerName }}"
          request_id: "{{ request_id }}"
          request_type: "CANCEL"
          external_id: "{{ external_id }}"
          user_email: "{{ user_email }}"
          cloudblue_template_id: "{{ cloudblue_template_id }}"
