    - name: Parse providers config map
      set_fact:
        providers_secret: "{{ secret_yaml | from_yaml }}"
    - name: Debug providers secret
      debug:
        var: providers_secret
    - name: Fail if provider tag not found
      fail:
        msg: "Nessuna entry per provider_client_tag: '{{ provider_client_tag }}'"
      when: provider_client_tag not in secret_yaml

    - name: Get provider config
      set_fact:
        provider_secret: "{{ providers_secret[provider_client_tag] }}"
    - name: Debug provider secret
      debug:
        var: provider_secret
    